apiVersion: apps/v1
kind: Deployment
metadata:
  name: ducks-test
spec:
  selector:
    matchLabels:
      app: blue-ducks
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: blue-ducks
    spec:
      containers:
        - name: blue-ducks
          image: steeloctopus/duckhunt:latest
          ports:
            - containerPort: 80